### ISSUE TITLE
Exception raised when cancelling future in a pool queue.

### ISSUE THREAD

**Issue by Kache** [meh/ruby-thread#40]
futures = []
    pool = Thread.pool(2)
    5.times do
      futures << Thread.future(pool) { sleep(5); Time.now }
    end
    sleep(6)
    futures.map { |f| f.value(0) } # some are completed, some are not
    futures.last.cancel # cancelling an incompleted future will raise

    NoMethodError: private method `raise' called for nil:NilClass
    	from ../ruby-2.2.0/gems/thread-0.2.1/lib/thread/pool.rb:86:in `raise'
    	from ../ruby-2.2.0/gems/thread-0.2.1/lib/thread/future.rb:78:in `block in cancel'
    	from ../ruby-2.2.0/gems/thread-0.2.1/lib/thread/future.rb:77:in `synchronize'
    	from ../ruby-2.2.0/gems/thread-0.2.1/lib/thread/future.rb:77:in `cancel'

Expected a Thread::Future::Cancel exception, as normal

**Comment by meh** [comment]
Can you try `master` if you have a non-synthetic test-case?

The test-case is fixed.

**Comment by Kache** [comment]
No exception thrown anymore.

For correctness though, `@exception` still isn't being set to the `Cancel` exception, so the future isn't marked `#cancelled?`

**Comment by meh** [comment]
Right, fixed that too.
